### ISSUE TITLE
Impossible to compile with Linux

### ISSUE THREAD

**Issue by lem-** [Mocahteam/ProgAndPlay#1]
First, you should not include like this:

    #include <rapidxml-1.13/rapidxml.hpp>

but without specifying the version:

    #include <rapidxml/rapidxml.hpp>

otherwise, people with newer versions cannot build.

Furthermore, by tapping only `make` as you write in the readme does not work: the file includes `windows.h`…

**Comment by Muratet** [comment]
Thank you for your test, I have not compiling Prog&Play on Linux for some time. I fix some problems and it compiles again (tested on Ubuntu 16.04).

I update the readme to give more informations.
